-- This module serves as the root of the `NavierStokesLedger` library.
-- Minimal version for clean mathematical proof
import NavierStokesLedger.BasicDefinitions
import NavierStokesLedger.PDEOperators
import NavierStokesLedger.TimeDependent
import NavierStokesLedger.VorticityLemmas
import NavierStokesLedger.EnergyEstimates
import NavierStokesLedger.RecognitionLemmas
import NavierStokesLedger.EnergyVorticityConnection
import NavierStokesLedger.SimplifiedProofs
import NavierStokesLedger.VectorCalculus
import NavierStokesLedger.NavierStokes
import NavierStokesLedger.VorticityBound
import NavierStokesLedger.BealeKatoMajda
import NavierStokesLedger.GlobalRegularity
