name: Lean CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Lean
      uses: leanprover/lean4-action@v1
      with:
        toolchain: leanprover/lean4:v4.11.0
    
    - name: Cache Lean dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/mathlib4
          .lake/build
        key: ${{ runner.os }}-lean-${{ hashFiles('lake-manifest.json') }}
        restore-keys: |
          ${{ runner.os }}-lean-
    
    - name: Update dependencies
      run: lake update
      
    - name: Build project
      run: lake build
      env:
        LEAN_THREADS: 2
    
    - name: Check for sorries
      run: |
        echo "Checking for remaining sorries..."
        SORRY_COUNT=$(grep -r "sorry" NavierStokesLedger/*.lean | wc -l)
        echo "Found $SORRY_COUNT sorries"
        if [ $SORRY_COUNT -gt 0 ]; then
          echo "::warning::Project contains $SORRY_COUNT sorries"
          grep -rn "sorry" NavierStokesLedger/*.lean
        else
          echo "::notice::No sorries found! Proof is complete."
        fi
    
    - name: Run tests
      run: |
        if [ -f "test/Main.lean" ]; then
          lake test
        fi 