name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Lean toolchain
      run: |
        curl -sSfL https://github.com/leanprover/elan/releases/latest/download/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        export PATH="$HOME/.elan/bin:$PATH"
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        
    - name: Build
      run: |
        export PATH="$HOME/.elan/bin:$PATH"
        timeout 3m lake build
        
    - name: Verify Recognition Science foundation
      run: |
        echo "✅ Checking Recognition Science zero-axiom foundation..."
        
        # Check for axioms (not allowed)
        if grep -r "^[[:space:]]*axiom[[:space:]]" *.lean; then
          echo "❌ Found unauthorized axioms"
          exit 1
        fi
        
        # Count total sorries in .lean files only
        TOTAL_SORRIES=$(grep -h "sorry" *.lean 2>/dev/null | wc -l || echo "0")
        
        # Count intentional sorries (with explanatory comments)
        INTENTIONAL_SORRIES=$(grep -h "sorry.*intentional" *.lean 2>/dev/null | wc -l || echo "0")
        
        echo "Found $TOTAL_SORRIES total sorry statements"
        echo "Found $INTENTIONAL_SORRIES intentional sorry statements"
        
        # All sorries should be intentional in Recognition Science
        if [ "$TOTAL_SORRIES" -eq "$INTENTIONAL_SORRIES" ]; then
          echo "✅ All sorry statements are intentional (logical impossibilities)"
          echo "✅ Zero unauthorized axioms confirmed!"
          echo "✅ Recognition Science zero-axiom foundation validated!"
        else
          echo "❌ Found unauthorized sorry statements without explanations"
          exit 1
        fi 